/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "media",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#fed01b",
        "surface-container-low": "#091328",
        "on-tertiary": "#645000",
        "surface": "#060e20",
        "background": "#060e20",
        "primary-fixed-dim": "#05a9e3",
        "on-secondary-container": "#c9cdff",
        "on-secondary-fixed": "#192490",
        "on-tertiary-fixed": "#433500",
        "surface-container-highest": "#192540",
        "surface-container-high": "#141f38",
        "on-tertiary-fixed-variant": "#645000",
        "secondary": "#8a95ff",
        "primary-fixed": "#2db7f2",
        "on-primary-container": "#002b3d",
        "inverse-surface": "#faf8ff",
        "on-error": "#490006",
        "on-primary-fixed": "#00121d",
        "tertiary-fixed-dim": "#eec200",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "secondary-fixed": "#cbceff",
        "tertiary-fixed": "#fed01b",
        "on-background": "#dee5ff",
        "primary-dim": "#05a9e3",
        "surface-container": "#0f1930",
        "on-primary": "#00374d",
        "surface-bright": "#1f2b49",
        "on-surface-variant": "#a3aac4",
        "secondary-fixed-dim": "#babfff",
        "on-tertiary-container": "#594700",
        "on-primary-fixed-variant": "#003a50",
        "primary": "#3bbffa",
        "surface-variant": "#192540",
        "on-secondary": "#000974",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#8a95ff",
        "outline": "#6d758c",
        "tertiary-dim": "#eec200",
        "inverse-primary": "#00668b",
        "inverse-on-surface": "#4d556b",
        "tertiary": "#ffe083",
        "error": "#ff716c",
        "on-error-container": "#ffa8a3",
        "on-surface": "#dee5ff",
        "outline-variant": "#40485d",
        "on-secondary-fixed-variant": "#3a45ad",
        "secondary-container": "#2f3aa3",
        "surface-dim": "#060e20",
        "surface-tint": "#3bbffa",
        "primary-container": "#22b1ec",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
};
